# Generated by Django 3.0.5 on 2022-11-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=50)),
                ('prod_price', models.IntegerField(default=0)),
                ('prod_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
